### ISSUE TITLE
Подготовка к реализации индекса на основе DiskANN

### ISSUE THREAD

**Issue by FArthur-cmd** [Vector-Similarity-Search-for-ClickHouse/ClickHouse#13]
Целью является ознакомление с проектом: собрать проект, научиться его запускать и использовать основные функции. Попробовать реализовать игрушечный индекс, чтобы убедиться в понимании структур

**Comment by JungleTryne** [comment]
Разработка началась реализацией простейшего skip-индекса, который пропускает гранулы по решению генератора случайности. Пулл-реквест: #12 

В дальнейшем планируется написание коннектора между ClickHouse и уже написанной реализацией индекса DiskANN, которая приведена в [этом репозитории](https://github.com/microsoft/DiskANN)

**Comment by FArthur-cmd** [comment]
Danila Mishin commented: Pull request: [https://github.com/Vector-Similarity-Search-for-ClickHouse/ClickHouse/pull/12]

(Не перенеслось с Github Issues, поэтому подкрепляю отдельным комментом)
