### ISSUE TITLE
Подготовка к реализации индекса на основе Faiss

### ISSUE THREAD

**Issue by FArthur-cmd** [Vector-Similarity-Search-for-ClickHouse/ClickHouse#16]
В данной задаче будет расмотрено устройство имплементации существующих индексов в ClickHouse, а именно: minmax индекс, set индекс. В процессе работы будут рассмотрены основные классы для работы с индексами, а также написан простейший skip индекс для понимания деталей работы интерфейсов.

**Comment by FArthur-cmd** [comment]
Nikita Evsiukov commented: h1. Итоги работы над задачей:

h2. Детали существующей имплементации
В процессе работы в первую очередь были уточнены детали использования индексов из Faiss в библиотеке [knowhere|https://github.com/milvus-io/knowhere]. Важные детали отражены в дополнении к моей [статье|https://workshop.samcs.ru/confluence/x/MAMbAg] про faiss. 

h2. Подготовка к имплементации в ClickHouse
В этой части были изучены интерфейсы для работы с индексами в ClickHouse. Также разобран код существующих индексов: [minmax|https://github.com/ClickHouse/ClickHouse/blob/8f9845722aeb9292dec70452f5752ba2ddc6ae15/src/Storages/MergeTree/MergeTreeIndexMinMax.h], [set|https://github.com/ClickHouse/ClickHouse/blob/8f9845722aeb9292dec70452f5752ba2ddc6ae15/src/Storages/MergeTree/MergeTreeIndexSet.h].

Для подготовки к реализации был написан простейший skip индекс, код которого находится в соответствующем PR.

**Comment by NikitaEvs** [comment]
#15

**Comment by FArthur-cmd** [comment]
Nikita Evsiukov commented: Статья про Faiss
